### ISSUE TITLE
Docs: when using the plugin from `netlify.toml` the readme should instruct users to install it as a dependency

### ISSUE THREAD

**Issue by erezrokah** [snyk-labs/netlify-plugin-snyk#1]
## Expected Behavior

The readme should instruct users to install the plugin as a dependency when using it from `netlify.toml`

## Current Behavior

The readme only instructs users to add the plugin to their `netlify.toml`

## Possible Solution

Update the section here https://github.com/snyk-labs/netlify-plugin-snyk#usage

## Steps to Reproduce (for bugs)

1. Follow the instructions and add the plugin via `netlify.toml`
2. Trigger a build on Netlify via a PR
3. See that the build fails

Example:
https://app.netlify.com/sites/determined-johnson-c85a62/deploys/5f5e238e3d43050007c55cd3

## Context

Discovered while reviewing https://github.com/netlify/plugins/pull/147

**Comment by lirantal** [comment]
Thanks Erez!
Adding as a dep is only required if you using the netlify config file, right? If so see the PR that fixes it now.

**Comment by erezrokah** [comment]
> Adding as a dep is only required if you using the netlify config file

Yes only when using via `netlify.toml`, PR looks good
