### ISSUE TITLE
Synk API key missing. (Occasionally)

### ISSUE THREAD

**Issue by 1mozolacal** [snyk-labs/netlify-plugin-snyk#14]
A deployment on Netlify without changes to it's deploy settings will state "Snyk API token missing". 
Builds were consistently failing, this was fix by install "netlify-plugin-snyk": "^1.3.1" as a dependency in the project. Although it doesn't consistently happen anymore, it will occasionally raise the error "API token missing". 
I have added the SNYK_TOKEN to environment variable.

## Expected Behavior
This error message isn't displayed.

## Current Behavior

Fails occasionally without changes to deploy settings.

## Possible Solution

My best guess is it is raise a separate error but still sending the message of "API token not found".

## Steps to Reproduce (for bugs)

Haven't been able to reproduce. Only happening to a single site, snyk plugin working as expect on all other sites.

## Context

prevents use of the plugin

## Your Environment

 node v16.10.0 (npm v7.24.0)

  "dependencies": {
    "@agility/content-fetch": "^1.1.1",
    "@netlify/functions": "^0.7.2",
    "@react-google-maps/api": "^2.2.0",
    "axios": "^0.21.4",
    "btoa": "^1.2.1",
    "js-cookie": "^3.0.1",
    "lodash": "^4.17.21",
    "netlify-plugin-snyk": "^1.3.1",
    "next": "11.1.2",
    "node-fetch": "^2.6.1",
    "react": "17.0.2",
    "react-dom": "17.0.2",
    "react-html-parser": "^2.0.2",
    "sass": "^1.39.2"
  },

**Comment by lirantal** [comment]
@1mozolacal any chance you have build logs that show more errors? anything that would help to chase this down.

Another thing I can think of is perhaps to try and run this on npm6 and not 7 just yet and see if it solves anything.

**Comment by lirantal** [comment]
I released a new version. Perhaps you could try again and let me know if the problem remains?

**Comment by 1mozolacal** [comment]
Sorry for the delay. This issue hasn't happened recently so it is safe to leave it as closed for the time being. 

I have attached a deploy log of a failed build.
[deploy_log.txt](https://github.com/snyk-labs/netlify-plugin-snyk/files/7421827/deploy_log.txt)

**Comment by lirantal** [comment]
Happy to hear. Let me know if it's otherwise coming back.
